version = 1

test_patterns = [
  "**/*.test.ts",
  "**/*.spec.ts"
]

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "logs/**",
  "public/**",
  "docs/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "vitest",
    "cypress",
    "nodejs"
  ]

[[code_formatters]]
name = "prettier"
